[build]
  functions = "netlify/functions"
  command = "apt-get update && apt-get install -y libnss3 libatk1.0-0 libatk-bridge2.0-0 libcups2 libdrm2 libxkbcommon0 libgbm1 && npm install && npm run build"